version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: banglamphu_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: banglamphuadmin
      MONGO_INITDB_ROOT_PASSWORD: banglamphuadmin32182
      MONGO_INITDB_DATABASE: banglamphu
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - banglamphu_network

  # Next.js Application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: banglamphu_nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://banglamphuadmin:banglamphuadmin32182@mongodb:27017/banglamphu?authSource=admin
      - NEXTAUTH_SECRET=your-nextauth-secret-key-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - JWT_SECRET=best32182
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyCRitEjWgFZcISNRHi-fz4o9dO6tejoRC4
      - BLOB_READ_WRITE_TOKEN=vercel_blob_rw_7O9CU7qtXjmK6YEd_Ki2aCayFKDV8mAMvmEZB36W6e9IDzo
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb
    networks:
      - banglamphu_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: banglamphu_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./public/uploads:/var/www/uploads:ro
    depends_on:
      - nextjs
    networks:
      - banglamphu_network

volumes:
  mongodb_data:
    driver: local

networks:
  banglamphu_network:
    driver: bridge
